# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gefplus/ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_GEF(object):
    def setupUi(self, GEF):
        GEF.setObjectName("GEF")
        GEF.resize(890, 436)
        icon = QtGui.QIcon()
        #icon.addPixmap(QtGui.QPixmap(absolute_path("static/logosmall.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        GEF.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(GEF)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        GEF.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GEF)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        icon1 = QtGui.QIcon()
        #icon1.addPixmap(QtGui.QPixmap(absolute_path("static/export.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuExport.setIcon(icon1)
        self.menuExport.setObjectName("menuExport")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        GEF.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GEF)
        self.statusbar.setObjectName("statusbar")
        GEF.setStatusBar(self.statusbar)
        self.actionImport = QtWidgets.QAction(GEF)
        icon2 = QtGui.QIcon()
        #icon2.addPixmap(QtGui.QPixmap(absolute_path("static/import.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon2)
        self.actionImport.setObjectName("actionImport")
        self.settings = QtWidgets.QAction(GEF)
        self.settings.setObjectName("settings")
        self.actionExport_Current = QtWidgets.QAction(GEF)
        self.actionExport_Current.setObjectName("actionExport_Current")
        self.actionCSV_csv = QtWidgets.QAction(GEF)
        self.actionCSV_csv.setObjectName("actionCSV_csv")
        self.actionSettings = QtWidgets.QAction(GEF)
        icon3 = QtGui.QIcon()
        #icon3.addPixmap(QtGui.QPixmap(absolute_path("static/settings.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSettings.setIcon(icon3)
        self.actionSettings.setObjectName("actionSettings")
        self.actionAutocomplete = QtWidgets.QAction(GEF)
        icon4 = QtGui.QIcon()
        #icon4.addPixmap(QtGui.QPixmap(absolute_path("static/autofill.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAutocomplete.setIcon(icon4)
        self.actionAutocomplete.setObjectName("actionAutocomplete")
        self.menuExport.addAction(self.actionExport_Current)
        self.menuExport.addAction(self.actionCSV_csv)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.actionSettings)
        self.menuData.addAction(self.actionAutocomplete)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(GEF)
        QtCore.QMetaObject.connectSlotsByName(GEF)

    def retranslateUi(self, GEF):
        _translate = QtCore.QCoreApplication.translate
        GEF.setWindowTitle(_translate("GEF", "GEF+"))
        self.menuFile.setTitle(_translate("GEF", "File"))
        self.menuExport.setTitle(_translate("GEF", "Export"))
        self.menuData.setTitle(_translate("GEF", "Data"))
        self.actionImport.setText(_translate("GEF", "New Import"))
        self.settings.setText(_translate("GEF", "Settings"))
        self.actionExport_Current.setText(_translate("GEF", "Text (.txt)"))
        self.actionCSV_csv.setText(_translate("GEF", "CSV (.csv)"))
        self.actionSettings.setText(_translate("GEF", "Settings"))
        self.actionAutocomplete.setText(_translate("GEF", "Autocomplete"))
